apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: order-dev

resources:
  - ../../apps/order-integration/overlays/dev
  - ../../apps/mock-order-api/base

images:
  - name: wiremock/wiremock
    digest: sha256:0d4ecb3e4dc8213fd7a4d37d6a78f6e6b553a6d2e15bd51b0999781282ac61b3